#默认使用配置
spring:
  profiles:
    active: dev
---
#公共配置与profiles选择无关
mybatis:
  type-aliases-package: com.yango.entity
  mapper-locations: classpath:com.yango.dao/*.xml

server:
  tomcat:
    uri-encoding: utf-8

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback-dev.xml
  level:
    org:
      springframework: INFO
    com:
      ibatis: DEBUG
    com.datacloudsec.collector.object.repository.mapper: DEBUG